version: '3.5'

volumes:
  bundle: 
  node_modules: 
  rails_cache: 
  packs: 
  db_data: 
  es_data:
    driver: local
  irb_history:

services:
  rails_base: &rails_base
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    tmpfs:
      - /tmp
    volumes:
      - ./src:/app
      - bundle:/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - rails_cache:/app/tmp/cache
      - ~/.ssh:/root/.ssh
      - irb_history:/root/irb_history
      - ./docker/web/.irbrc:/root/.irbrc
      - ./docker/web/entrypoint.sh:/entrypoint.sh
      # - ../layers_of_london-booth-map_tool:/layers_of_london-booth-map_tool
    stdin_open: true
    tty: true
  web:
    <<: *rails_base
    ports:
      - 3000:3000
    command: rails s -b 0.0.0.0
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker

  webpacker:
    <<: *rails_base
    ports:
      - 3035:3035
    command: ./bin/webpack-dev-server
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  
  shell:
    <<: *rails_base
    command: bash

  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./config/docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - db_data:/var/lib/mysql
      - ./src/database/import:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=layers-app_development
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    labels:
      - maintainer='jordi@error.agency'
  redis:
    image: redis:3.2
    ports:
      - '6379:6379'
    labels:
      - maintainer='jordi@error.agency'

  elasticsearch:
    build:
      context: .
      dockerfile: docker/elasticsearch/Dockerfile
    ports:
      - "9200:9200"
      - "8080:8080"
    environment:
      xpack.security.enabled: 'false'
      # LOGSPOUT: 'ignore'
      # ES_JAVA_OPTS: '-Xms1024m -Xmx1024m'
      # bootstrap.memory_lock: 'false'
      discovery.type: 'single-node'
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    #   nofile:
    #     soft: 262144
    #     hard: 262144
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-SsfL", "127.0.0.1:9200/_cat/health?h=status"]
      interval: 10s
      timeout: 1s
      retries: 10

  mailhog:
    command: ["-smtp-bind-addr", "0.0.0.0:2525"]
    user: root
    image: mailhog/mailhog
    ports:
      - 2525:2525
      - 8025:8025



