class AddAutogeneratedTrackerToRecords < ActiveRecord::Migration[5.2]
  def change
    add_column :records, :autogenerated_date_from_fields, :text
    add_column :records, :autogenerated_date_to_fields, :text
  end
end
