# config/chewy.yml
# separate environment configs
test:
  host: 'elasticsearch:9200'
  prefix: 'test'
development:
  host: 'elasticsearch:9200'
  prefix: <%= ENV['ELASTIC_SEARCH_PREFIX'] || Rails.env %>