source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# ruby '2.5.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.2'
# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.4.4'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
# gem 'sass-rails', '~> 5.0'  
gem 'sassc-rails'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', "~>3"
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'mini_racer', platforms: :ruby

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
gem 'redis-rails'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'faker'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'awesome_print'
  # gem 'debase'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'rubocop'
  # gem 'ruby-debug-ide'
  gem 'web-console', '>= 3.3.0'
  # gem 'errorstudio_capistrano_recipes', git: 'ssh://git@bitbucket.org/errorstudio/errorstudio_capistrano_recipes'
  # gem 'slickplan', path: '~/dev/slickplan'
  # gem 'terminal-table'
  gem 'bullet'

  gem 'bundler-audit'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

# group :staging, :production do
#   gem 'passenger'
# end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

gem 'devise'
gem 'devise_invitable'

# Minimal authorization through OO design and pure Ruby classes
gem 'pundit'

gem 'rooftop', git: "https://github.com/rooftopcms/rooftop-ruby"
# gem 'rooftop', path: "~/dev/rooftop-ruby"
gem 'rooftop-rails', git: "https://github.com/rooftopcms/rooftop-rails"
# gem 'rooftop-rails', path: "~/dev/rooftop-rails"
gem 'rooftop-rails-extras', git: "https://github.com/rooftopcms/rooftop-rails-extras"

# Decorators/View-Models for Rails Applications
gem 'draper'

# Ruby state machines
gem 'aasm'

# High-level Elasticsearch Ruby framework based on the official elasticsearch-ruby client
gem 'chewy'

# A gem to automate using jQuery with Rails
gem 'jquery-rails'

# Image manipulation
gem 'mini_magick'

gem 'image_processing', '~> 1.2'

# Parse youtube URLs to get the ID.
gem 'youtube_id'

# Carrierwave is needed for alpha migration
gem 'carrierwave'
gem 'carrierwave-base64'

# Geocoder needed for the alpha migration
gem 'geocoder'

# S3 gem for activestorage
gem 'aws-sdk-s3', require: false

gem 'activeadmin'

#ES6 for the marketing site
gem 'sprockets-es6'

# OJ for fast json parsing
gem 'oj'

gem 'rollbar'

gem 'simple_errors', git: "https://github.com/errorstudio/simple_errors"

gem 'roboto'

gem 'activeadmin_quill_editor'

gem 'activeadmin-searchable_select'

gem 'acts_as_list'

gem 'activeadmin-orderable'

gem 'rubyXL'

gem 'switch_user'

gem 'georeferencer', git: "https://github.com/layersoflondon/georeferencer-ruby"
# gem 'georeferencer', path: '../../../georeferencer'

gem 'friendly_id'

gem 'sitemap_generator'

gem 'rubyXL'

gem 'rinku'

# gem 'layers_of_london-booth-map_tool', path: "../../layers_of_london-booth-map_tool"
gem 'layers_of_london-booth-map_tool', git: "https://github.com/layersoflondon/booth-maptools"

gem 'natural_sort'

gem 'browser'

gem 'sidekiq'